# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20161111_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
